### ISSUE TITLE
Split PREFIX from DESTDIR

### ISSUE THREAD

**Issue by Leont** [tadzik/panda#101]
Currently, the only way to select the installation directory in panda is DESTDIR. This is confusing two concepts that are quite well defined in other toolchains:

* A prefix is an alternative final install location, for example `/usr/local/bla` or `/home/users/perl6`
* A destdir is a temporary staging directory for the purpose of packaging. Setting it to `/var/deb/staging/rakudo` should mean files get installed to something like `/var/deb/staging/rakudo/usr/lib/perl6/`. It's prepended, but doesn't otherwise affect the logic.

Currently panda supports a `DESTDIR` environmental variable with semantics of a prefix argument. This is rather unfortunate, and will make life for packagers harder later on.

**Comment by tadzik** [comment]
Fixed in https://github.com/tadzik/panda/commit/43525de12f6e296bb4b16a43d09fa5e6da54c5b7

**Comment by tadzik** [comment]
(We don't actually support DESTDIR at all, but I don't think it's actually needed for anything at this point).
