### ISSUE TITLE
[request] Test modules with 'and' without blib

### ISSUE THREAD

**Issue by ugexe** [tadzik/panda#115]
For instance where modules don't work correctly/pass tests when compiled it would be useful to be able to test with panda but without the compiled units:

    [nickl@db-server perl6-html-parser-xml]$ panda install XML::Query
    ==> Fetching XML::Query
    ==> Building XML::Query
    Compiling lib/XML/Query/Results.pm6 to mbc
    Compiling lib/XML/Query/Statement.pm6 to mbc
    Compiling lib/XML/Query.pm6 to mbc
    ==> Testing XML::Query
    t/basic.t .. Default constructor for 'Query' only takes named arguments

To check if this is the compiled unit's fault, you do:

    [nickl@db-server perl6-html-parser-xml]$ panda look XML::Query
    ==> Fetching XML::Query
    ==> Entering /home/nickl/CFB/tmp/perl6-html-parser-xml/.panda-work/1416245028_1 with /bin/bash
    [nickl@db-server 1416245028_1]$ panda-test
    t/basic.t .. ok
    All tests successful.

If withp6lib was modified to include blib OR lib you could test each case individually. Furthermore another variable could be added to the `reporter` branch's json to report these types of failures as well as inform that user.

**Comment by tadzik** [comment]
Panda doesn't precompile anymore, so that ceased to be a problem :)
