### ISSUE TITLE
install dependencies of local project

### ISSUE THREAD

**Issue by szabgab** [tadzik/panda#129]
Would it be possible to add a command line option that would install all the dependencies of a module (but not the module itself) and if that could work for the project in the "current directory"?

That would be very useful for someone who clones a repository of a module and wants to test the module (and maybe even patch it), but does not want to install it.

```panda installdeps .```

**Comment by ugexe** [comment]
This is what i've been using for Travis-CI testing:

    perl6 -MJSON::Tiny -e 'shell("panda install "~from-json("META6.json".IO.slurp).<depends>)'

**Comment by dwarring** [comment]
There's a pull request open https://github.com/tadzik/panda/pull/128 to do this.

**Comment by tadzik** [comment]
Pull request now merged; thanks!
