### ISSUE TITLE
Exit codes possibly not correct on FreeBSD

### ISSUE THREAD

**Issue by ugexe** [tadzik/panda#130]
Gives false results for FreeBSD for both build-passed and test-passed, but only sometimes

- Build fails but is marked as passed
http://testers.perl6.org/report/dist/Cache::Memcached/7149

- Tests fail but are marked as passed
http://testers.perl6.org/report/dist/Sum/8688

- Same environment as previous test (Sum), but fails as it should:
http://testers.perl6.org/report/dist/Slang::SQL/8814

- But 3 days earlier the previous module (Slang::SQL) fails its test but is marked as pass:
http://testers.perl6.org/report/dist/Slang::SQL/8215

Could this be the culprit?
https://github.com/tadzik/panda/commit/e5a9ef297422acb8d9754dbae91ab42b0c3d2702

**Comment by usev6** [comment]
Huh, those tests are from my box. It's possible that there is something wrong with my test setup. I hope I'll find some time to investigate later today. Otherwise I'll disable the test reports for the next runs (until I found time to take a closer look).

**Comment by ugexe** [comment]
Could you try using a slightly older panda commit, as in sometime prior to
12/28? Or running the prove test command manually and seeing what the exit
code is?

**Comment by usev6** [comment]
OK, the first check: The actual exit code for testing Slang::SQL is 1 -- but "Result: PASS" is printed: https://gist.github.com/usev6/e551c9a3f6f659b6d5a5

That's still with the same panda version as the test report in http://testers.perl6.org/report/dist/Slang::SQL/8814

**Comment by usev6** [comment]
Hmm, that's obviously because in "p6prove" we have

my $result = $tests == $passes ?? 'PASS' !! 'FAIL';

In this case $tests=0 and $passes=0, so 'PASS' is printed.

**Comment by ugexe** [comment]
panda still uses 'prove' as the test command

**Comment by usev6** [comment]
Second check: The actual exit code for building Cache::Memcached is also 1: https://gist.github.com/usev6/1bc768a8e5bea87e5764

**Comment by ugexe** [comment]
What I originally suspected was either capturing stderr or using pipe on FreeBSD somehow does not play nicely with TAP::Harness.

**Comment by usev6** [comment]
Okay, I added the output with prove (which looks just right: https://gist.github.com/usev6/e551c9a3f6f659b6d5a5

**Comment by ugexe** [comment]
Need to test with capturing stderr. Panda uses the following command:

    prove -e perl6 -r t/ 2>&1

Panda actually calls the above with pipe, so you would also want to test:

    # testme.pl6
    my $handle = pipe("$cmd 2>&1", :r);
    my $passed = $handle.close.status == 0;
    say $passed ?? "passed" !! "failed";

**Comment by usev6** [comment]
$ cat testme.pl6 
my $cmd = "prove -e perl6 -r t/";
my $handle = pipe("$cmd 2>&1", :r);
my $passed = $handle.close.status == 0;
say $passed ?? "passed" !! "failed";
$ perl6 testme.pl6 
passed

====

$ cat testme.pl6
my $cmd = "prove -e perl6 -r t/";
#my $handle = pipe("$cmd 2>&1", :r);
my $handle = pipe("$cmd", :r);
my $passed = $handle.close.status == 0;
say $passed ?? "passed" !! "failed";
$ perl6 testme.pl6
Cannot locate native library 'libsqlite3.so'
  in method postcircumfix:<( )> at lib/NativeCall.pm6:130
  in method connect at lib/DBDish/SQLite.pm6:221
  in method connect at lib/DBIish.pm6:9
  in block <unit> at t/01_basic.t:11

passed

**Comment by ugexe** [comment]
To clarify that its the pipe command:

15:29 <bartolin> I'm trying with 'prove -e perl6 -r t/ 2>&1 now
15:31 <bartolin> from the command line that still returns 'FAIL' and exit code 1

**Comment by usev6** [comment]
For the sake of completeness

* testme.pl6 gives the correct result when I sleep a few seconds before closing the handle:
```
$ cat testme.pl6
my $cmd = "prove -e perl6 -r t/";
my $handle = pipe("$cmd 2>&1", :r);
sleep 2;
my $passed = $handle.close.status == 0;
say $passed ?? "passed" !! "failed";
$ perl6 testme.pl6
failed
```

* here's the bug report for rakudo: https://rt.perl.org/Ticket/Display.html?id=123563
