### ISSUE TITLE
The @ARGS hack is shit

### ISSUE THREAD

**Issue by tadzik** [tadzik/panda#134]
https://github.com/tadzik/panda/blob/master/bin/panda#L14 assumes switches don't have arguments, which is false, as it breaks https://github.com/tadzik/panda/blob/master/bin/panda#L54

**Comment by Mouq** [comment]
Is this a Rakudo problem with arg parsing?

**Comment by tadzik** [comment]
Well, the reason I have this thing in place is because of the way Rakudo, or perhaps Perl 6 by spec does arg parsing. In my ideal world model it wouldn't be necessary in the first place.
