### ISSUE TITLE
Not compatible with File__Find when bootstrap?

### ISSUE THREAD

**Issue by Nuk9** [tadzik/panda#135]
When I run `perl6 bootstrap.pl` command under panda directory, it returns the following error:
Could not find lib in any of: /home/xuzhao/git/panda/ext/File__Find/lib

I have checked and the ext/File__Find/lib folder does exist.

**Comment by tadzik** [comment]
Hmm, is it still happening? What if you remove and re-clone panda directory? What's your platform?

**Comment by Nuk9** [comment]
I recloned panda repo and this problem is already fixed.

**Comment by tadzik** [comment]
Good to know. Thanks, and sorry for the wait.
