### ISSUE TITLE
panda errors out on first invocation after rakudo star update

### ISSUE THREAD

**Issue by mgruner** [tadzik/panda#140]
While updating homebrew to rakudo star 2015.02 I noticed one small issue with panda on at least the Mac OS platform. On the first call after the update, panda bails out with the error `Found no writable directory into which panda could be installed`. After that, everything works as it should.

**Comment by tadzik** [comment]
Is that perhaps happening each time you invoke ```panda update```?

**Comment by mgruner** [comment]
I believe it only happens after upgrading to a new rakudo star release.

Am 16.04.15 um 16:32 schrieb Tadeusz Sośnierz:
> Is that perhaps happening each time you invoke |panda update|?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tadzik/panda/issues/140#issuecomment-93749331>.
> 

-- 
Martin Gruner
Senior Developer R&D

OTRS AG
Bahnhofplatz 1a
94315 Straubing

T: +49 (0)6172 681988 0
F: +49 (0)9421 56818 18
I:  www.otrs.com/

Geschäftssitz: Bad Homburg, Amtsgericht: Bad Homburg, HRB 10751,
USt-Nr.: DE256610065
Aufsichtsratsvorsitzender: Burchard Steinbild, Vorstand: André
Mindermann (Vorsitzender), Christopher Kuhn, Sabine Riedel

Schlanker, schneller und flacher denn je - OTRS 4! Und für alle, die
MEHR wollen: Entdecken Sie hier die OTRS Business Solution™ mit mehr
Business Features!
https://www.otrs.com/otrs-business-solution-fuer-besseren-kundenservice/?lang=de

**Comment by tadzik** [comment]
But it otherwise works just as it should, right? Installing new modules (ones not included in Star) etc?

**Comment by mgruner** [comment]
Yes.

Am 16.04.15 um 16:35 schrieb Tadeusz Sośnierz:
> But it otherwise works just as it should, right? Installing new modules
> (ones not included in Star) etc?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tadzik/panda/issues/140#issuecomment-93750088>.
> 

-- 
Martin Gruner
Senior Developer R&D

OTRS AG
Bahnhofplatz 1a
94315 Straubing

T: +49 (0)6172 681988 0
F: +49 (0)9421 56818 18
I:  www.otrs.com/

Geschäftssitz: Bad Homburg, Amtsgericht: Bad Homburg, HRB 10751,
USt-Nr.: DE256610065
Aufsichtsratsvorsitzender: Burchard Steinbild, Vorstand: André
Mindermann (Vorsitzender), Christopher Kuhn, Sabine Riedel

Schlanker, schneller und flacher denn je - OTRS 4! Und für alle, die
MEHR wollen: Entdecken Sie hier die OTRS Business Solution™ mit mehr
Business Features!
https://www.otrs.com/otrs-business-solution-fuer-besseren-kundenservice/?lang=de

**Comment by stmuk** [comment]
I suspect this is because panda is being invoked from a directory without write perms since it tries to write out files relative rather than absolute.
