### ISSUE TITLE
smoke is testing locally installed modules

### ISSUE THREAD

**Issue by ugexe** [tadzik/panda#142]
I have a module that is not in the ecosystem that I installed earlier via `panda install .` and when I later did `panda smoke` it eventually attempted to test the local module. 

I would think default behavior for smoke would be to only test modules in official ecosystem, especially if you are submitting test reports (as sending a test report for a module not in the ecosystem gives a connection error). 

Perhaps I am mistaken and the proper way to do this is to do `panda update` first?

**Comment by tadzik** [comment]
Not mistaken, smoking locally installed stuff doesn't make sense :) I'll take a look at it.

**Comment by ugexe** [comment]
As far as I can tell its fixed now

**Comment by tadzik** [comment]
Awesome.
