### ISSUE TITLE
help displays full path?

### ISSUE THREAD

**Issue by zengargoyle** [tadzik/panda#157]
Is there a reason for the full path to panda being displayed? 

$ panda help
Usage:
  /home/hayter/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda [--notests] [--nodeps] install [<modules> ...] -- Install the specified modules
  /home/hayter/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda [--notests] installdeps [<modules> ...] -- Install dependencies, but don't build the modules themselves
  /home/hayter/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda [--installed] [--verbose] list -- List all available modules
...

It also seems a bit slower to start than I remember...

$ time panda help
...
real    0m9.592s
user    0m9.428s
sys     0m0.128s

**Comment by tadzik** [comment]
Yeah, that's related to CompUnitRepos a while ago, both of those. @FROGGS may know more about that, and when can we see it fixed :)

**Comment by lizmat** [comment]
> On 09 May 2015, at 11:55, Tadeusz Sośnierz <notifications@github.com> wrote:
> 
> Yeah, that's related to CompUnitRepos a while ago, both of those. @FROGGS may know more about that, and when can we see it fixed :)

Could this be related to 66b713de7307c3eae4f275  ??

Make $?FILE absolute always
Relative paths are useless when debugging problems with module loading.



Liz

**Comment by tadzik** [comment]
I think it's more the fault of the way rakudobrew does shims:
```> cat `which panda`
#!/bin/sh
/home/tadzik/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda "$@"```

When invoked differently, the end result is much more readable:
```PATH=/home/tadzik/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin:$PATH panda help
Usage:
  panda [--notests] [--nodeps] install [<modules> ...] -- Install the specified modules
  panda [--notests] installdeps [<modules> ...] -- Install dependencies, but don't build the modules themselves
  panda [--installed] [--verbose] list -- List all available modules
  panda [--installed] revdep <name> -- Show reverse dependencies
(yada yada yada)```

So I'm going to fix that in rakudobrew itself.
