### ISSUE TITLE
Collect warnings and standard error output from module builds/tests

### ISSUE THREAD

**Issue by hoelzro** [tadzik/panda#161]
I would like to have the Perl 6 smokers report whether a distribution's tests are passing but spitting out warnings so that authors can have a heads up when they're getting deprecation warnings.  I wanted to open this issue to promote some discussion on the topic instead of just thinking about it by myself. =)

Currently, deprecation warnings are simply printed to standard error; this could be better, but I think it would be acceptable to treat any output on standard error as a warning for now.  I know that right now, panda merges standard output and error into a single stream; I was thinking of implementing a new module for calling out to a subprocess and keeping the streams separate.

**Comment by hoelzro** [comment]
@FROGGS @tadzik When you two have a moment, I would love to have some feedback on this idea!

**Comment by colomon** [comment]
It would be great to support this in emmentaler and the smoke reports...

**Comment by hoelzro** [comment]
@colomon That's the plan =)

**Comment by tadzik** [comment]
I long long (yes, really) for something like IPC::Open3 that.Perl 5 has, perhaps it can be done with NativeCall? ISTR it's just calling someone posix-y function.

**Comment by FROGGS** [comment]
Well, we also want to make it work on windows, no? So I think we need to extend nqp::openpipe...

**Comment by FROGGS** [comment]
I... already have sketched out the new API for pipe() and how I'd implement it... does it make sense to share these kind of details somewhere?

**Comment by hoelzro** [comment]
Windows compatability would be ideal, but my primary focus is to get it working on POSIX systems so that the smoke reports benefit from this.  @FROGGS If you want to share those ideas here, feel free!

**Comment by ugexe** [comment]
Fwiw I think this can already be done with Proc::Async

github.com/ugexe/zef/blob/master/lib/Zef/Test/Result.pm6

**Comment by hoelzro** [comment]
Wow, thanks for that @ugexe!  I've been holding off pending the merge of @FROGGS' openpipe3 branch, but I think I could just use `Proc::Async`.

**Comment by FROGGS** [comment]
Hi, the said branch was merged and run() as well as shell() allow to capture stdout and stderr while writing to stdin.

**Comment by hoelzro** [comment]
\o/ I just implemented the code to this, closing.
