### ISSUE TITLE
Reverse dependencies doesn't respect --notests

### ISSUE THREAD

**Issue by hoelzro** [tadzik/panda#167]
If you do this:

    panda install --notests JSON::Tiny

when panda goes to install its reverse dependencies (ie. panda), it forces `$notests` off.

**Comment by tadzik** [comment]
Oh, bummer :/ Well, the whole panda-doing-precompilation and thus also revdeps is going to get scratched soon, so this won't be an issue then at least.

**Comment by tadzik** [comment]
Panda doesn't precomp or revdep anymore, so that's off the list :)
