### ISSUE TITLE
validate that downloaded file is JSON

### ISSUE THREAD

**Issue by Zhtwn** [tadzik/panda#171]
Stupid proxies can replace the downloaded file with HTML error messages while reporting 200 OK. Need to validate that the downloaded file is JSON before saving into the file.

Example: installing panda, I got this for the project.json file:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head><title>408 Request Timeout</title></head>
<body><h1>Request Timeout</h1>
<p>Server timeout waiting for the HTTP request from the client.</p>
<hr><address>Apache/2.4.10 (Debian) Server at design.perl6.org Port 80</address></body></html>
```

Once the `projects.json` file is not JSON, panda crashes when trying to read the file.

**Comment by flussence** [comment]
Don't panic, it's not a stupid proxy problem, just a malformed request. The PR I just sent should stop it happening again.
