### ISSUE TITLE
Panda::Ecosystem deprecation warning

### ISSUE THREAD

**Issue by drforr** [tadzik/panda#195]
Saw 1 occurrence of deprecated code.
================================================================================
Method send (from IO::Socket) seen at:
  lib/Panda/Ecosystem.pm, line 81
Deprecated since v2015.7, will be removed with release v2015.9!
Please use print instead.
--------------------------------------------------------------------------------
Please contact the author to have these occurrences of deprecated code
adapted, so that this message will disappear!

Please note that *ALL* deprecated features will be removed at the RC-0 release
(expected September 2015).

**Comment by tadzik** [comment]
This got fixed in 96c3793cb7f0e4271f266135170d20032eeae963
