### ISSUE TITLE
OSX: build and test failures get installed

### ISSUE THREAD

**Issue by ugexe** [tadzik/panda#199]

**Comment by tadzik** [comment]
It sounds like OSX (or prove on OSX) is setting exitcode differently for https://github.com/tadzik/panda/blob/master/lib/Panda/Common.pm#L108.

Could you add a ```note $p.result.exitcode``` in there and tell me what it says when building/testing fails?

**Comment by ugexe** [comment]
Coincidentally it appears to be a rakudobug related to promises not getting sunk properly on OSX I submitted a RT for. https://rt.perl.org/Public/Bug/Display.html?id=125758

 It can be worked around via:

    $p.result; # add me
    $p.result.exitcode;

which assures the process is finished (for the sake of this bug) before `.exitcode` is called. While ugly, it appears to have no other side effects on other OSs so could simply be grepped out in the future.

PR: https://github.com/tadzik/panda/pull/201
