### ISSUE TITLE
Traceback when invoked as «panda list»

### ISSUE THREAD

**Issue by will-crawford** [tadzik/panda#200]
Method 'chars' not found for invocant of class 'Any'
  in method dispatch:<hyper> at /home/william/share/perl6/runtime/CORE.setting.moarvm:1
  in sub listprojects at /home/william/share/perl6/lib/Panda/App.pm:53
  in sub MAIN at /home/william/share/perl6/site/bin/panda:34
  in block <unit> at /home/william/share/perl6/site/bin/panda:87

**Comment by will-crawford** [comment]
I _think_ this can be fixed with something like:

    my $max-ver   = @projects».version».grep({$_}).chars.max;

but there's still a couple of "undefined value" warnings from «panda --verbose list» and it's possible someone might specify version as "0" ...

**Comment by tadzik** [comment]
I don't get that locally. Can you send me your copy of projects.json from panda's directory on which it occurs to you?

**Comment by will-crawford** [comment]
Sure I can ... how would you like it? I can't see an email address here anywhere; and the Gist interface doesn't seem to have anywhere to attach a file ... (but I can probably paste it in there if need be).

**Comment by tadzik** [comment]
You can gist it, it's plaintext with no metadata, should be fine :)

**Comment by will-crawford** [comment]
will-crawford/70336d37b94284b7c936

**Comment by tadzik** [comment]
I just tried it with fresh panda and I don't get any errors. Is it possible that it was fixed since it was reported? Do you still get it on updated panda?

**Comment by will-crawford** [comment]
I've built MoarVM and nqp fresh from git, and get the error from both a fresh build of rakudo star (July) and after building rakudo from git but installing the modules from star. It still happens after doing "panda install panda". The projects.json appears to be installed by star modules-install-m target. Can I substitute a different one to see what happens?

**Comment by tadzik** [comment]
```panda update``` should update projects.json to the list from http://ecosystem-api.p6c.org/projects.json

**Comment by will-crawford** [comment]
... then `panda install panda` fails with:

    ==> Fetching panda
    fetch stage failed for panda: source-url meta info missing
      in method install at /home/william/share/perl6/lib/Panda.pm:121
      in method resolve at /home/william/share/perl6/lib/Panda.pm:218
      in sub MAIN at /home/william/bin/panda:20
      in block <unit> at /home/william/bin/panda:87

**Comment by will-crawford** [comment]
I'm giving up for now :)

**Comment by will-crawford** [comment]
Although I don't think I meant to actually close it ...

**Comment by tadzik** [comment]
Oh, yeah, I might have broken that recently :/ Should be fixed now though.
