### ISSUE TITLE
Ensure panda is tagged for each Rakudo release

### ISSUE THREAD

**Issue by softmoth** [tadzik/panda#207]
Testing Perl6 with Travis-CI suggests installing a versioned panda to match the rakudo version in use: http://docs.travis-ci.com/user/languages/perl6/

The suggested install method is `rakudobrew build-panda ${TRAVIS_PERL6_VERSION}`, e.g. `2015.07`. However, panda currently has tags for 2015.03 – 2015.06, but not for 2015.07.

This is exacerbated because panda HEAD doesn't build with Rakudo 2015.07, so it's not feasible to leave off the version.

For an example of the problem using HEAD with older Rakudo, see https://travis-ci.org/softmoth/p6-Template-Mustache/jobs/77567891#L889
```
==> Installing panda from a local directory '/home/travis/.rakudobrew/moar-2015.07/panda'
Could not download module metadata: Too many positionals passed; expected 1 argument but got 2
  in sub die at /home/travis/.rakudobrew/moar-2015.07/install/share/perl6/runtime/CORE.setting.moarvm:1
  in method update at /home/travis/.rakudobrew/moar-2015.07/panda/lib/Panda/Ecosystem.pm:110
  in method init-projects at /home/travis/.rakudobrew/moar-2015.07/panda/lib/Panda/Ecosystem.pm:48
  in method get-project at /home/travis/.rakudobrew/moar-2015.07/panda/lib/Panda/Ecosystem.pm:119
  in method get-deps at /home/travis/.rakudobrew/moar-2015.07/panda/lib/Panda.pm:166
  in method resolve at /home/travis/.rakudobrew/moar-2015.07/panda/lib/Panda.pm:209
  in sub MAIN at bin/panda:18
  in block <unit> at bin/panda:95
```

To work around the lack of a tag for 2015.07, I hacked my .travis.yml config to force the checkout of an earlier commit:  https://github.com/softmoth/p6-Template-Mustache/blob/master/.travis.yml

**Comment by paultcochrane** [comment]
Have just added the 2015.07 tag.  Hopefully it builds alright for you now.  Sorry for the omission!

**Comment by softmoth** [comment]
Yes, it works now. Thanks!
