### ISSUE TITLE
Cannot build panda with newsest rakudo

### ISSUE THREAD

**Issue by teodozjan** [tadzik/panda#216]
$ rakudobrew build-panda
    Cloning into 'panda'...
    remote: Counting objects: 4294, done.
    remote: Total 4294 (delta 0), reused 0 (delta 0), pack-reused 4293
    Receiving objects: 100% (4294/4294), 721.13 KiB | 144.00 KiB/s, done.
    Resolving deltas: 100% (1925/1925), done.
    Checking connectivity... done.
    No need to rebootstrap, running normal bootstrap
    ==> Bootstrapping Panda
    Type check failed in assignment to '$prefix'; expected 'Str' but got 'List'
      in sub MAIN at bootstrap.pl:22
      in block <unit> at bootstrap.pl:7
    
    Done, built panda for moar-nom
    Updating shims
    $  perl6 --version
    This is perl6 version 2015.07.1-963-g32ce653 built on MoarVM version 2015.08-40-gbfb2236

Done on fully clean rakudobrew

**Comment by pnu** [comment]
rakudo/rakudo@63a883f is the first commit that makes this fail.

**Comment by teodozjan** [comment]
https://github.com/tadzik/panda/commit/5a056da41d566aada52775d0a1b741d4a0634af1
