### ISSUE TITLE
Undeclared routine: Did you mean '&uniq'?

### ISSUE THREAD

**Issue by GildedHonour** [tadzik/panda#224]
$ perl6 bootstrap.pl
===SORRY!=== Error while compiling /home/alex/apps/perl6/panda/ext/File__Find/lib/File/Find.pm
Undeclared routine:
    unit used at line 3. Did you mean '&uniq'?

**Comment by niner** [comment]
What rakudo version do you use? unit has been there since about May AFAIK.

**Comment by GildedHonour** [comment]
@niner  

$ perl6 --version
This is perl6 version 2013.12 built on parrot 5.9.0 revision 0

**Comment by niner** [comment]
That's soon 2 years old. Please upgrade to a current rakudo first. The experience will be much improved :)

**Comment by GildedHonour** [comment]
@niner , I installed it a couple months ago.

**Comment by paultcochrane** [comment]
Did you install Perl6 from e.g. the Debian packages?  If so, then you've definitely got an outdated version (an update to Rakudo/Perl6 on MoarVM for Debian is, however, in the works).  The way to quickly get an up to date version of Perl 6 would be to use [rakudobrew](https://github.com/tadzik/rakudobrew).  Assuming a Unix-like system, you'd need to do something like the following:

    git clone https://github.com/tadzik/rakudobrew ~/.rakudobrew
    export PATH=~/.rakudobrew/bin:$PATH
    rakudobrew build moar    # will build an install Rakudo atop the MoarVM virtual machine
    rakudobrew build-panda   # will install an up to date panda

Hope that helps!

**Comment by GildedHonour** [comment]
@paultcochrane , yes, thanks.
