### ISSUE TITLE
Use basename in usage message

### ISSUE THREAD

**Issue by ilmari** [tadzik/panda#231]
The usage message for panda includes the full path on every line, which makes it hard to read, as all lines wrap.  Using `$*PROGRAM.basename` would make it more readable.

**Comment by slobo** [comment]
Latest version includes `sub USAGE` and doesn't suffer from this.

**Comment by ilmari** [comment]
Ah, that's a lot better. Closer investigation reveals that the issue was due to the rakudobrew shim masking the actual panda executable in `$PATH`, which causes Rakudo's built-in usage generator to show the full path, and `File::Spec::Unix.canonpath()` not resolving `..` elements.
