### ISSUE TITLE
Linenoise fails in rebootstrap but installs fine via direct install

### ISSUE THREAD

**Issue by paultcochrane** [tadzik/panda#236]
I happened to notice a repeatable problem.  With `Linenoise` already installed, and after updating the MoarVM/NQP/Rakudo stack followed by a `./rebootstrap.pl` in `panda`, `Linenoise` fails its tests with the following output:

    ==> Testing Linenoise
    Could not find file 'Build.pm' for module Build.pm
      in block  at /home/cochrane/Projekte/OSSProjekte/perl6/MoarVM/install/share/perl6/site/lib/Panda/Tester.pm:10
      in sub indir at /home/cochrane/Projekte/OSSProjekte/perl6/MoarVM/install/share/perl6/site/lib/Panda/Common.pm:20
      in method test at /home/cochrane/Projekte/OSSProjekte/perl6/MoarVM/install/share/perl6/site/lib/Panda/Tester.pm:5
      in method install at /home/cochrane/Projekte/OSSProjekte/perl6/MoarVM/install/share/perl6/site/lib/Panda.pm:141
      in method resolve at /home/cochrane/Projekte/OSSProjekte/perl6/MoarVM/install/share/perl6/site/lib/Panda.pm:219
      in sub MAIN at bin/panda:18
      in block <unit> at bin/panda:145

However, if one simply installs `Linenoise` directly

    ./bin/panda install Linenoise

no such error appears and `Linenoise` installs without a problem.

Any idea as to why this may be?

**Comment by niner** [comment]
Closing since rebootstrap.pl is gone and thus the issue should be void.
