### ISSUE TITLE
JSON::Fast tests block panda install

### ISSUE THREAD

**Issue by teodozjan** [tadzik/panda#247]
==> Fetching JSON::Fast
     ==> Building JSON::Fast
     ==> Testing JSON::Fast
     t/01-parse.t ...... ok
     t/02-structure.t .. ok
     t/03-unicode.t .... ok
     at 67: can't parse objects starting in F yet
       in sub parse-thing at /home/travis/.rakudobrew/moar-nom/panda/.panda-work/1448285181_3/lib/JSON/Fast.pm:272
       in sub parse-obj at /home/travis/.rakudobrew/moar-nom/panda/.panda-work/1448285181_3/lib/JSON/Fast.pm:167
       in sub from-json at /home/travis/.rakudobrew/moar-nom/panda/.panda-work/1448285181_3/lib/JSON/Fast.pm:291
       in block <unit> at t/04-roundtrip.t:36
     # Looks like you planned 17 tests, but ran 16
     t/04-roundtrip.t .. 
     Dubious, test returned 255 (wstat 65280, 0xff00)
     Failed 1/17 subtests 

https://github.com/timo/json_fast/issues/6

**Comment by muraiki** [comment]
I'm also having this problem. `perl6 version 2015.11-47-g99e23c3 built on MoarVM version 2015.11`

**Comment by timo** [comment]
hi, i've just put a new commit into json_fast that outputs more information with this exception. can you try cloning timo/json_fast and running perl6 -Ilib t/04-roundtrip.t for me and give me the output?

**Comment by muraiki** [comment]
Thanks for the quick response!

```
1..17
ok 1 - Int
ok 2 - Rat
ok 3 - Str
ok 4 - Str with quote
ok 5 - Undef
ok 6 - other escapes
ok 7 - Non-ASCII
ok 8 - Empty Array
ok 9 - Array of Int
not ok 10 - Array of Num# TODO known type mismatches

# Failed test 'Array of Num'
# at t/04-roundtrip.t line 38
# expected: $[1.3, 2.8, 32323423.4, 4.0]
#      got: $[1.3, 2.8, 32323423.4, 4]
ok 11 - Array of Str
ok 12 - Empty Hash
ok 13 - Hash of Int
ok 14 - Hash of Num
ok 15 - Hash of Str
ok 16 - Array of Stuff
at 67: can't parse objects starting in F yet (context: alse,")
  in sub parse-thing at /root/temp/json_fast/lib/JSON/Fast.pm:277
  in sub parse-obj at /root/temp/json_fast/lib/JSON/Fast.pm:171
  in sub from-json at /root/temp/json_fast/lib/JSON/Fast.pm:296
  in block <unit> at t/04-roundtrip.t:36

# Looks like you planned 17 tests, but ran 16
```

**Comment by tadzik** [comment]
@timo++'s fix to both JSON::Fast and panda confirmed to fix the issue. Thanks to you all :) Closing.
