### ISSUE TITLE
Error running bootstrap.pl on OSX 10.11.1 (MoarVM)

### ISSUE THREAD

**Issue by jbest84** [tadzik/panda#259]
$ perl6 -c bootstrap.pl 
===SORRY!===
Function 'CompUnit::Repository' needs parens to avoid gobbling block
at /Users/jbest2/code/panda/bootstrap.pl:29
------>         }⏏<EOL>
Missing block (apparently claimed by 'CompUnit::Repository')
at /code/panda/bootstrap.pl:30

I added parens around the if statement on line 29 to work around the issue.

**Comment by niner** [comment]
Current panda is no longer compatible with a rakudo older than a couple of days. Unfortunately due to the upcoming Perl 6.c release, we don't have enough time to go through a deprecation cycle for these changes.
Sorry for the inconvenience!
