### ISSUE TITLE
Panda-build start up problems

### ISSUE THREAD

**Issue by sylvarant** [tadzik/panda#260]
The `panda-build` is not working properly on both my mac and linux environments.
Here's a printout from travis-ci:
```
Cannot unbox a type object
  in sub MAIN at /home/travis/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda-build:10
  in block <unit> at /home/travis/.rakudobrew/bin/../moar-nom/install/share/perl6/site/bin/panda-build:2
```
The problem centers around a line:
```perl6
@binaries = flat @installations.map: { .files('bin/panda-build') };
``` 
But it's not clear to me what is wrong with it

**Comment by teodozjan** [comment]
It is not panda

See this https://travis-ci.org/teodozjan/lacuna-cookbuk/builds/95056774
I have to install deps twice because first fails on form.

**Comment by sylvarant** [comment]
So this is an issue with rakudo ?

**Comment by teodozjan** [comment]
IMHO doesn't look like compilation error. Did you try `export MVM_SPESH_DISABLE=1` before running panda?

**Comment by sylvarant** [comment]
Neither installing the dependencies twice or doing the export make a difference here.
I am starting to think this is a problem with the rakudo type checker

**Comment by sylvarant** [comment]
Ok this issue has stop showing up in recent builds, so I assume whatever was broken somewhere in the chain has been.
