### ISSUE TITLE
creates a folder "(HANDLED) Failed to open file"

### ISSUE THREAD

**Issue by cognominal** [tadzik/panda#263]
panda bootstrap.pl seems to succed and creates a folder "(HANDLED) Failed to open file".
Trying to install R* with panda Task::Star fails.

$ per6 bootstrap.pl
...
All tests successful.
Files=5, Tests=31, 25 wallclock secs ( 0.05 usr  0.02 sys + 22.56 cusr  2.17 csys = 24.80 CPU)
Result: PASS
==> Installing panda
==> Successfully installed panda
$ panda install Task::Star
===SORRY!===
Could not find Shell::Command:ver<True>:auth<True>:api<True> in:
    /Users/cog/.perl6/2015.11-514-g5b6cbc7
    /usr/local/share/perl6/site
    /usr/local/share/perl6/vendor
    /usr/local/share/perl6
    CompUnit::Repository::NQP<4469177968>
    CompUnit::Repository::Perl5<4469175600>
$ perl6 -v
This is rakudo version 2015.11-514-g5b6cbc7 built on MoarVM version 2015.11-44-ge7edb06 implementing Perl v6.b.

**Comment by tadzik** [comment]
That doesn't replicate here anymore on latest rakudo and latest panda. Does it still happen to anyone?

**Comment by Ovid** [comment]
It's happening to me on OS X.

```
$ panda install Linenoise
===SORRY!===
Could not find Shell::Command in:
    /Users/ovid/.perl6/2015.12-24-g373adc0
    /Users/ovid/.rakudobrew/moar-nom/install/share/perl6/site
    /Users/ovid/.rakudobrew/moar-nom/install/share/perl6/vendor
    /Users/ovid/.rakudobrew/moar-nom/install/share/perl6
    CompUnit::Repository::AbsolutePath<4403187744>
    CompUnit::Repository::NQP<4403184336>
    CompUnit::Repository::Perl5<4403181176>
```

**Comment by niner** [comment]
A lot of fixes to both rakudo and panda went in since the last comment including a definite fix to "(HANDLED) Failed to open file" and fixes for discrepancies between panda's state file and what's actually installed.
Can anyone still reproduce this?

**Comment by cognominal** [comment]
On Saturday, January 9, 2016, niner <notifications@github.com> wrote:

> A lot of fixes to both rakudo and panda went in since the last comment
> including a definite fix to "(HANDLED) Failed to open file" and fixes for
> discrepancies between panda's state file and what's actually installed.
> Can anyone still reproduce this?
>
Nope. Thx. Panda is getting better every day.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tadzik/panda/issues/263#issuecomment-170236806>.
>


-- 
cognominal stef

**Comment by tadzik** [comment]
I guess it's closable then. Thanks for reporting, and please reopen if it happens again :)
