### ISSUE TITLE
Panda bootstrap.pl fails with moar-2015.11 when using rakudobrew build-panda

### ISSUE THREAD

**Issue by ravenhall** [tadzik/panda#265]
$ rakudobrew build-panda
Cloning into 'panda'...
remote: Counting objects: 4565, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 4565 (delta 6), reused 0 (delta 0), pack-reused 4542
Receiving objects: 100% (4565/4565), 777.21 KiB | 573.00 KiB/s, done.
Resolving deltas: 100% (2065/2065), done.
Checking connectivity... done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
===SORRY!===
Function 'CompUnit::Repository' needs parens to avoid gobbling block
at /home/nwaddell/.rakudobrew/moar-2015.11/panda/bootstrap.pl:30
------>         }⏏<EOL>
Missing block (apparently claimed by 'CompUnit::Repository')
at /home/nwaddell/.rakudobrew/moar-2015.11/panda/bootstrap.pl:31
------>         }⏏<EOL>

Failed running /home/nwaddell/.rakudobrew/bin/../moar-2015.11/install/bin/perl6 bootstrap.pl at /home/nwaddell/.rakudobrew/bin/rakudobrew line 57.
        main::run("/home/nwaddell/.rakudobrew/bin/../moar-2015.11/install/bin/pe"...) called at /home/nwaddell/.rakudobrew/bin/rakudobrew line 502
        main::build_panda(undef) called at /home/nwaddell/.rakudobrew/bin/rakudobrew line 120
Thu Dec 17 03:47 PM nwaddell@orcrist.hilton.com ~/.rakudobrew/bin $ rakudobrew build-panda
Already on 'master'
Your branch is up-to-date with 'origin/master'.
===SORRY!===
Function 'CompUnit::Repository' needs parens to avoid gobbling block
at /home/nwaddell/.rakudobrew/moar-2015.11/panda/bootstrap.pl:30
------>         }⏏<EOL>
Missing block (apparently claimed by 'CompUnit::Repository')
at /home/nwaddell/.rakudobrew/moar-2015.11/panda/bootstrap.pl:31
------>         }⏏<EOL>

Failed running /home/nwaddell/.rakudobrew/bin/../moar-2015.11/install/bin/perl6 bootstrap.pl at /home/nwaddell/.rakudobrew/bin/rakudobrew line 57.
        main::run("/home/nwaddell/.rakudobrew/bin/../moar-2015.11/install/bin/pe"...) called at /home/nwaddell/.rakudobrew/bin/rakudobrew line 502
        main::build_panda(undef) called at /home/nwaddell/.rakudobrew/bin/rakudobrew line 120

**Comment by zakame** [comment]
Also failing on moar v6.c :(

```
~ $ rakudobrew build moar v6.c
[...]
Rakudo has been built and installed.
Updating shims
Done, moar-v6.c built
~ $ rakudobrew build-panda
Already on 'master'
Your branch is up-to-date with 'origin/master'.
===SORRY!===
Function 'CompUnit::Repository' needs parens to avoid gobbling block
at /home/zakame/.rakudobrew/moar-nom/panda/bootstrap.pl:30
------>         }⏏<EOL>
Missing block (apparently claimed by 'CompUnit::Repository')
at /home/zakame/.rakudobrew/moar-nom/panda/bootstrap.pl:31
------>         }⏏<EOL>

Failed running /home/zakame/.rakudobrew/bin/../moar-nom/install/bin/perl6 bootstrap.pl at /home/zakame/.rakudobrew/bin/rakudobrew line 57.
	main::run("/home/zakame/.rakudobrew/bin/../moar-nom/install/bin/perl6 bo"...) called at /home/zakame/.rakudobrew/bin/rakudobrew line 502
	main::build_panda(undef) called at /home/zakame/.rakudobrew/bin/rakudobrew line 120
```

**Comment by niner** [comment]
Closing as with commit f97efa5bc91726891341f87eb96c2476535fbaeb we now check the Perl 6 version in bootstrap.pl which should de-confuse users.
