### ISSUE TITLE
Options not working anymore

### ISSUE THREAD

**Issue by hankache** [tadzik/panda#278]
Options are not working anymore:
`panda --installed list` returns the full list.  
`panda --notests` still run tests.  
`panda --nodeps` still try to install deps.  
`panda --force` is not forcing anything. This is the most problematic as we were using it as a workaround to #269 and now anyone building a fresh rakudobrew/rakudo/panda cannot build any module that depends on the same modules that panda needs (JSON::Fast File::Find Shell::Command)

These were the ones I tested.

**Comment by shadowcat-mst** [comment]
Currently looks like a rakudobug - if you revert to a straight up 2015.12 you should be fine. Tests to narrow it down are running as I type this.

**Comment by shadowcat-mst** [comment]
Please try updating to  https://github.com/rakudo/rakudo/commit/2ae0dfaba6

**Comment by hankache** [comment]
@shadowcat-mst ++ Options are now working again
