### ISSUE TITLE
installing File::Find breaks panda

### ISSUE THREAD

**Issue by daleevans** [tadzik/panda#282]
It looks like it's possible to install File::Find even though it is installed automatically, possible because it is installed as a dependency.  Unfortunately, once it is installed, panda can no longer function, and trying to run panda results in "P6M Merging GLOBAL symbols failed: duplicate definition of symbol Find" errors, presumably because there are now two slightly different File::Find modules installed at the same time.

$ panda install File::Find
==> Fetching File::Find
==> Building File::Find
==> Testing File::Find
t/01-file-find.t .. ok
All tests successful.
Files=1, Tests=11,  3 wallclock secs ( 0.02 usr  0.00 sys +  3.13 cusr  0.13 csys =  3.28 CPU)
Result: PASS
==> Installing File::Find
==> Successfully installed File::Find
$ panda
===SORRY!===
P6M Merging GLOBAL symbols failed: duplicate definition of symbol Find
===SORRY!===
P6M Merging GLOBAL symbols failed: duplicate definition of symbol Find
===SORRY!===
P6M Merging GLOBAL symbols failed: duplicate definition of symbol Find

**Comment by daleevans** [comment]
fixed by https://github.com/tadzik/panda/commit/aa89bca25ef7c0f1208a6af81364c9a64d68e710

**Comment by niner** [comment]
commit aa89bca did not fix this issue.

**Comment by niner** [comment]
This should really be fixed for good in commit 3734ea8d37 and panda commit d03b5abb5edd2f0e5c0f8579ab1126e67d3f28ee

One possibly needs to remove precompiled files to benefit from these fixes.
