### ISSUE TITLE
Cannot install some of the modules

### ISSUE THREAD

**Issue by musiKk** [tadzik/panda#287]
I installed perl6 (moar-vm) and panda via rakudobrew. Then I tried to install Readline as per the suggestion of the perl6 repl. This does not work although the [modules list](https://modules.perl6.org/) has it; I'm getting a `Readline not found in the ecosystem` error. `panda update` produces no output so I cannot verify if it works or not (returns 0 though). `panda search Readline` produces no output (which is expected by now). `panda list | wc -l` says 500. According to the modules directory there should be 512. So something with the update does not seem to work for me.

If you can, please help me with a suggestion how I can provide you with actual information on how to debug this issue.

**Comment by musiKk** [comment]
FWIW it works now. The number of modules listed with `panda list` also corresponds to the number of packages given on the modules Web site. Maybe the API was unreachable or not up to date...

**Comment by tadzik** [comment]
Sounds like the module ecosystem API was having a hiccup. I'm going to close it for now, but if it happens again, please reopen the issue and attach the projects.json that panda has downloaded so we can look into it. Thanks!
