### ISSUE TITLE
What is "official" panda version ? 0.1 or 2016-02 ?

### ISSUE THREAD

**Issue by dod38fr** [tadzik/panda#297]
Hello

META.info mentions panda 'version" : "0.1"', but github [release page](https://github.com/tadzik/panda/releases) provides version similar to rakudo versions.

As Debian packager, this situation is confusing and may break Debian tools: some tools like uscan can only detect version from github's release page.

I've also uploaded a [panda package for Debian](http://ftp-master.debian.org/new/perl6-panda_2015.12-1.html) that rely on tagged release. Please tell me asap if you really want panda version to be "0.1" instead of 2016-02

All the best

**Comment by tadzik** [comment]
Hello dod38fr,
Thanks a lot for pointing it out. The version number in the META.info has indeed been seriously neglected and not reflecting the actual state of things. The tags are there so to indicate the last rakudo version that said release works on, as in: if you run rakudo version 2016.02, you cannot expect newer version of panda to work on it, as "2016.02 plus one commit".

These days rakudo has a mostly stable version that modules will be able to rely on for a while, but I think it makes sense to stick to the date-like versioning scheme, at least for now. Thanks for bringing this to my attention, and I promise to try to keep better track of panda's metadata.

**Comment by paultcochrane** [comment]
Just to let you know, I just changed the version number in 6d1a33b to use a date-based version string.  I also bumped it up to agree with the current tag.

**Comment by tadzik** [comment]
http://i.imgur.com/9s390o4.gif

**Comment by dod38fr** [comment]
Thanks :smiley:
