### ISSUE TITLE
Latest Panda with Rakudo 2016.07 failing: Could not find Shell::Command

### ISSUE THREAD

**Issue by TimothyXL** [tadzik/panda#328]
So I've tried both rakudobrew install as well as manual install.

The Rakudo Star version is 2016.07, Panda has been installed from the master branch.

Output from perl6 bootstrap.pl:

> Cloning into 'panda'...
>remote: Counting objects: 4951, done.
>remote: Total 4951 (delta 0), reused 0 (delta 0), pack-reused 4951
>Receiving objects: 100% (4951/4951), 865.31 KiB | 1.17 MiB/s, done.
>Resolving deltas: 100% (2251/2251), done.
>==> Bootstrapping Panda
>==> Installing panda from a local directory '/home/tmtvl/perl6/panda'
>==> panda depends on File::Find, Shell::Command, JSON::Fast, File::Which
>==> Shell::Command depends on File::Find
>==> Fetching File::Find
>==> Building File::Find
>==> Testing File::Find
>t/01-file-find.t .. ok
>All tests successful.
>Files=1, Tests=11,  1 wallclock secs ( 0.02 usr  0.00 sys +  0.84 cusr  0.04 csys =  0.90 CPU)
>Result: PASS
>==> Installing File::Find
>==> Please make sure that /home/tmtvl/perl6/rakudo-star/share/perl6/site/bin is in your PATH

Output from running panda:

>===SORRY!===
>Could not find Shell::Command at line 2 in:
>    /home/tmtvl/.perl6
>    /home/tmtvl/perl6/rakudo-star/share/perl6/site
>    /home/tmtvl/perl6/rakudo-star/share/perl6/vendor
>    /home/tmtvl/perl6/rakudo-star/share/perl6
>    CompUnit::Repository::AbsolutePath<54546240>
>    CompUnit::Repository::NQP<47643456>
>    CompUnit::Repository::Perl5<47643496>

Running perl -e 'require Shell::Command;' returns fine, so I'm not sure what the problem is, unless I need to copy the module from ~/.perl5 to ~/.perl6?

**Comment by ugexe** [comment]
`perl -e 'require Shell::Command'` is not the same as `perl6 -e 'require Shell::Command'` These are two different modules for two different languages that happen to have the same name. This doesn't explain why its not attempting to fetch Shell::Command though.

You might try installing `panda` with `zef` to see if its a problem with your Rakudo install or `panda`, although at that point you may as well just use `zef` in place of `panda` altogether.

**Comment by TimothyXL** [comment]
Right, I'll give it a try. In the meantime I have found that moar-2016.02 installed via rakudobrew together with the appropriate panda version works perfectly fine for me.

I'll let you know if I find out anything.

**Comment by stmuk** [comment]
I believe this could be a dup of https://github.com/MoarVM/MoarVM/issues/410

**Comment by stmuk** [comment]
@TimothyXL Not many (maybe some) are seeing this on linux. Is there anything special about your system?

**Comment by TimothyXL** [comment]
Maybe? I'm on OpenSUSE Tumbleweed, I use plenv so I can user Perl 5.24 for everything, and my default shell is zsh.

Next weekend I'll try and do some debugging.
