### ISSUE TITLE
Panda tries to access network when it doesn't need to

### ISSUE THREAD

**Issue by flussence** [tadzik/panda#51]
I ran into this problem while running without a network connection, I'd just ran bootstrap.pl (which worked) and tried to install a local module with no deps (which didn't). It looks like it unconditionally wants to download the json modules list if it doesn't have a local copy yet.

**Comment by tadzik** [comment]
Same problem with 'panda help', as described in #64 (closing it as duplicate).

**Comment by tadzik** [comment]
This should work now :)
