### ISSUE TITLE
Missing or wrong version of dependency when installed module used also in bootstrap

### ISSUE THREAD

**Issue by bbkr** [tadzik/panda#53]
Rakudo 2013.07
Panda 7b2d7b2afb (HEAD at the moment of writing this issue)

1. Bootstrap Panda
2. Do panda `install JSON::Tiny`
3. Try to install any other module

Following error occurs:
```
Missing or wrong version of dependency 'lib/JSON/Tiny/Grammar.pm'
```

**Comment by tadzik** [comment]
Still a problem :(

One of the ways it could be solved is for panda to, each time it installs something, go through the list of all the installed modules and find those that depend on what we just installed and rebuild these as well.

**Comment by tadzik** [comment]
Fixed. Panda will now rebuild all installed reverse dependencies after updating a module.
