### ISSUE TITLE
Bootstrap script presents "successful run" info after failed run.

### ISSUE THREAD

**Issue by lue** [tadzik/panda#61]
==> Fetching Shell::Command
    ==> Building Shell::Command
    Compiling lib/Shell/Command.pm to pir
    build stage failed for Shell::Command: Failed building lib/Shell/Command.pm
    ==> Please make sure that /home/lue/.perl6/2013.10-315-ga6eeb0b/bin is in your PATH

This makes trying to run `panda` annoying when you only scan the end result of the output ☺.

**Comment by tadzik** [comment]
(I'm gonna assume it is)
