### ISSUE TITLE
Add support for HTTP proxies which require authentication

### ISSUE THREAD

**Issue by Siddhant** [tadzik/panda#89]
At lib/Panda/Ecosystem.pm:70, panda assumes that the environment variable $http_proxy contains only host and port information:

    my ($host, $port) = %*ENV<http_proxy>.split('/').[2].split(':');

However, the general format can be:

    http_proxy=http://username:password@hostname:port/

where username and password are used to authenticate a HTTP(S) proxy.
Currently, if username and password are present in $http_proxy, panda breaks.
Kindly add support for proxies which require authentication.

**Comment by tadzik** [comment]
Will be fixed by #147

**Comment by tadzik** [comment]
Delegated to #185
