### ISSUE TITLE
dir '.work' not created on Windows

### ISSUE THREAD

**Issue by meisl** [tadzik/panda#98]
I'm on WinXP 32, using Rakudo * 2014.03.01 (built on parrot 6.1.0 revision 0). It's the latest .msi for Windows but just a few days ago 2014.08.30 came out and hopefully there'll be an .msi for that soon.

So, possibly - and hopefully, this might be a non-issue soon. I'll check and close it if that's the case.

Problem: 
e.g. `panda install Grammar::Debugger`
fails with
`could not create work tree dir 'E:\perl6\foo\.work\1409682366_1'.: No such file or directory`

Workaround:
create the scratch folder by hand, i.e. `mkdir "E:\perl6\foo\.work"` for this example.
(panda removes it once done)

p.s.: 035ffc6995c says "Rename '.work' to '.panda-work'", so...

**Comment by meisl** [comment]
Haven't looked at it since then, so I still have to try again with the newest stuff.

But, @tadzik, what exactly do you mean by "how to tackle that"?
I mean: has it been made a bit more particular, somewhat isolated - or is it still generally unresolved/unknown why/-or even if- it's still not working on Win?

In case of the former: plz provide some hints where to look and I'll try to put my being Windows-savvy to test :)

**Comment by meisl** [comment]
Hi,

pretty much the same as I just commented on #99:
- am willing to look into it (again), *but*
- need latest 2015-02 .msi s
- & would appreciate some kind of hint where to start looking (in the source)

Thx

**Comment by azawawi** [comment]
Is this still valid with the latest rakudo?

**Comment by meisl** [comment]
@azawawi: just tried with Rakudo* 2015.03 on Win32 - and it works. I figure 51fc726008 fixed it but I'm not sure.
@FROGGS: may I ask you again to make the .msi for the latest 2015.06? I think I should confirm that it works with that as well before closing this issue. Thx in advance :)

**Comment by meisl** [comment]
Thanks to @FROGGS++ (https://github.com/rakudo/star/issues/47) I can confirm that it also works with 2015.06.
